# https://registry.hub.docker.com/_/nginx/
FROM nginx:latest

# nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# HTML
COPY index.html /usr/share/nginx/html/index.html

# https://qiita.com/nexkeh/items/02a4d6c33d884bda1b23
